In [2]:
import pandas as pd

In [3]:
info = {
    "Name" : ["Rahul", "Shivam", "rishi","Gyan Bhai"],
    "CGPA" : [9.5 ,8.5,7.4,9.2]
}
df = pd.DataFrame(info)

print(df)
print(type(df))

        Name  CGPA
0      Rahul   9.5
1     Shivam   8.5
2      rishi   7.4
3  Gyan Bhai   9.2
<class 'pandas.core.frame.DataFrame'>

In [4]:
df

        Name  CGPA
0      Rahul   9.5
1     Shivam   8.5
2      rishi   7.4
3  Gyan Bhai   9.2

In [5]:
s = pd.Series([1,2,3,4,5])
print(s)
print(type(s))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
#index
print(s[3])
print(s[0])

4
1

In [7]:
s = pd.Series([11,12,13,19,22] , index = ["Carl","Tom","Bittu","Riya","Manjul"])
print(s)
print(s["Riya"])
print(s["Manjul"])
print(s.iloc[0])
print(s.index)

Carl      11
Tom       12
Bittu     13
Riya      19
Manjul    22
dtype: int64
19
22
11
Index(['Carl', 'Tom', 'Bittu', 'Riya', 'Manjul'], dtype='object')

In [8]:
#sum of the 2 series.
s1 =pd.Series([11,12,13,19,22])
s2 = pd.Series([1,1,1,1,1])
print(s1+s2)
s1[0] = 50
print(s1+s2)

0    12
1    13
2    14
3    20
4    23
dtype: int64
0    51
1    13
2    14
3    20
4    23
dtype: int64

In [9]:
changed_s1 = s1.drop(0)
print(s1)
print(changed_s1)

0    50
1    12
2    13
3    19
4    22
dtype: int64
1    12
2    13
3    19
4    22
dtype: int64

In [10]:
#dataframe
info = {
    "Name" : ["Rahul", "Shivam", "rishi","Gyan Bhai"],
    "Age" :[21, 20, 22, 23],
    "CGPA" : [9.5 ,8.5,7.4,9.2]
}
df = pd.DataFrame(info)


print(df)
print(type(df))
print(df.index)
print(df.columns)

        Name  Age  CGPA
0      Rahul   21   9.5
1     Shivam   20   8.5
2      rishi   22   7.4
3  Gyan Bhai   23   9.2
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=4, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='object')

In [11]:
df = pd.DataFrame([["Manjul",22], ["Shivam",20], ["Rahul",21]],columns = ["Name","Age"])
print(df)

     Name  Age
0  Manjul   22
1  Shivam   20
2   Rahul   21

In [12]:
import numpy as np 
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr,columns = ["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [13]:
#load csv
df = pd.read_csv("employee_data.csv")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [14]:
#load json
df = pd.read_json("employees.json")
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000

In [15]:
#Methods
print(df.head()) #starting 5 rows

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000

In [16]:
print(df.tail())# last 5 rows

   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000

In [17]:
print(df.sample()) # for any random row

   ID Name  Age Department  Salary
4   5  Eva   38         IT   65000

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [19]:
print(df.shape)# to know the wor,columns

(10, 5)

In [20]:
df. describe()# to describe our data

             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000

In [21]:
df.columns# to know the columns details

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')

In [22]:
df.nunique()# to know the unique numbers

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [23]:
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [24]:
df.head()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017

In [25]:
df.tail()

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [26]:
df.describe()

,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
count,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000,18000.000000
mean,23.065980,37.655560,40.369131,70.152228,32.055176,6.035508,48.065100,0.800595,104.645556,21.510251,57.714351,5.283910
std,26.156536,78.600701,17.647450,24.999440,13.820680,2.454790,14.950849,0.250254,25.616070,9.509444,18.844908,2.741712
min,-37.814000,-123.121000,0.025000,0.061000,0.013000,0.003000,0.114000,0.000000,16.000000,5.000000,25.002000,0.500000
25%,12.972000,2.352000,27.904500,53.125500,22.362500,4.360750,38.028500,0.633000,87.000000,13.357750,41.320000,2.937000
50%,29.232000,42.146000,40.286500,69.961000,32.019500,6.026000,48.142000,0.800500,103.000000,21.455500,57.847000,5.297000
75%,41.008000,103.820000,52.436250,87.256500,41.364250,7.715250,58.258500,0.969000,121.000000,29.688250,74.234750,7.662000
max,60.170000,174.763000,115.683000,161.810000,90.019000,16.559000,103.016000,1.832000,231.000000,37.998000,89.997000,9.999000

In [27]:
df["city"]

0        New York
1        New York
2        New York
3        New York
4        New York
           ...
17995      Zurich
17996      Zurich
17997      Zurich
17998      Zurich
17999      Zurich
Name: city, Length: 18000, dtype: object

In [28]:
df[["city","pm10", "aqi"]]

           city     pm10  aqi
0      New York  108.938  108
1      New York   63.043   90
2      New York   82.553   84
3      New York   79.951  158
4      New York   66.423   97
...         ...      ...  ...
17995    Zurich   74.179  103
17996    Zurich   47.988  105
17997    Zurich   72.908  122
17998    Zurich   95.152   95
17999    Zurich   30.411   88

[18000 rows x 3 columns]

In [29]:
df.loc[2]# to access the one label

timestamp      2025-11-04 20:25:17.554219
country                                US
city                             New York
latitude                           40.713
longitude                         -74.006
pm25                                42.25
pm10                               82.553
no2                                26.935
so2                                 9.538
o3                                  23.32
co                                  0.977
aqi                                    84
temperature                        31.833
humidity                           62.783
wind_speed                           9.65
Name: 2, dtype: object

In [30]:
df.loc[0:3]#starting index to ending index

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956

In [31]:
df.iloc[[2]]# a access the one index rows

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.25,82.553,26.935,9.538,23.32,0.977,84,31.833,62.783,9.65

In [32]:
df.loc[0,"aqi"] # To know a any index of any data

np.int64(108)

In [33]:
df.loc[0:36,["country" ,"city", "aqi"]]

   country      city  aqi
0       US  New York  108
1       US  New York   90
2       US  New York   84
3       US  New York  158
4       US  New York   97
5       US  New York   92
6       US  New York  155
7       US  New York  115
8       US  New York  121
9       US  New York   76
10      US  New York   96
11      US  New York   99
12      US  New York  114
13      US  New York  124
14      US  New York  121
15      US  New York   91
16      US  New York  130
17      US  New York  127
18      US  New York   87
19      US  New York  151
20      US  New York  102
21      US  New York  102
22      US  New York   49
23      US  New York  115
24      US  New York   76
25      US  New York  113
26      US  New York  113
27      US  New York  109
28      US  New York  106
29      US  New York  121
30      US  New York  101
31      US  New York  129
32      US  New York  109
33      US  New York  121
34      US  New York   86
35      US  New York  108
36      US  New York   69

In [34]:
df.columns

Index(['timestamp', 'country', 'city', 'latitude', 'longitude', 'pm25', 'pm10',
       'no2', 'so2', 'o3', 'co', 'aqi', 'temperature', 'humidity',
       'wind_speed'],
      dtype='object')

In [42]:
df.iloc[33:44, 2:12]

,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi
33,New York,40.713,-74.006,60.560,63.448,47.080,7.569,53.451,0.660,121
34,New York,40.713,-74.006,43.347,60.078,29.800,5.121,33.756,0.597,86
35,New York,40.713,-74.006,9.159,40.718,43.378,1.136,55.258,0.384,108
36,New York,40.713,-74.006,24.582,54.865,27.669,6.068,70.059,0.712,69
37,New York,40.713,-74.006,60.768,80.058,28.523,5.186,59.795,0.603,121
38,New York,40.713,-74.006,22.522,111.308,25.565,4.773,47.249,0.656,111
39,New York,40.713,-74.006,22.819,44.810,34.010,4.025,72.560,0.727,85
40,New York,40.713,-74.006,34.911,61.065,23.065,5.959,69.458,0.763,69
41,New York,40.713,-74.006,27.682,57.714,39.407,3.983,26.519,0.233,98
42,New York,40.713,-74.006,56.166,70.246,50.209,11.169,63.496,0.678,125
43,New York,40.713,-74.006,24.610,36.188,17.424,7.383,40.406,0.223,49

In [56]:
#cell access
df.at[1,"city"]

'New York'

In [73]:
#filtering data
#filtering data single line 
df[df["aqi"]>100]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
8,2025-11-05 02:25:17.554219,US,New York,40.713,-74.006,60.914,44.775,40.936,6.779,36.751,1.014,121,24.092,48.148,8.686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787
17993,2025-11-19 11:25:17.554219,CH,Zurich,47.377,8.542,76.613,37.495,29.662,5.419,57.042,1.103,153,20.437,79.602,2.663
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660

In [67]:
#filtering data to find a specific things
df[df["no2"]<6]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
99,2025-11-08 21:25:17.554219,US,New York,40.713,-74.006,28.589,46.458,1.252,4.613,54.452,1.019,57,28.134,27.374,2.585
152,2025-11-11 02:25:17.554219,US,New York,40.713,-74.006,32.981,90.472,4.891,6.073,34.687,0.976,90,6.430,40.777,9.852
175,2025-11-12 01:25:17.554219,US,New York,40.713,-74.006,40.269,48.789,5.748,5.035,52.005,0.654,80,10.603,48.530,5.464
226,2025-11-14 04:25:17.554219,US,New York,40.713,-74.006,44.250,83.417,1.819,9.634,63.057,0.111,88,17.197,32.595,0.591
256,2025-11-15 10:25:17.554219,US,New York,40.713,-74.006,41.904,3.347,4.424,7.354,33.211,0.376,83,13.580,80.338,8.541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17568,2025-11-16 18:25:17.554219,FI,Helsinki,60.170,24.938,49.471,70.450,3.879,3.647,62.212,0.676,98,25.879,29.066,2.558
17596,2025-11-17 22:25:17.554219,FI,Helsinki,60.170,24.938,73.736,83.998,1.977,6.281,46.863,1.039,147,21.737,70.312,8.156
17705,2025-11-07 11:25:17.554219,CH,Zurich,47.377,8.542,47.779,48.225,3.542,7.068,36.900,1.135,95,6.185,69.317,5.973
17837,2025-11-12 23:25:17.554219,CH,Zurich,47.377,8.542,37.584,70.151,4.209,6.880,34.269,0.512,75,32.037,39.232,4.120
17951,2025-11-17 17:25:17.554219,CH,Zurich,47.377,8.542,56.553,54.765,2.930,7.967,26.985,0.133,113,23.582,31.741,3.718

In [74]:
#filtering data to some logics
df[(df["no2"]<6) &(df["temperature"]<30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
99,2025-11-08 21:25:17.554219,US,New York,40.713,-74.006,28.589,46.458,1.252,4.613,54.452,1.019,57,28.134,27.374,2.585
152,2025-11-11 02:25:17.554219,US,New York,40.713,-74.006,32.981,90.472,4.891,6.073,34.687,0.976,90,6.430,40.777,9.852
175,2025-11-12 01:25:17.554219,US,New York,40.713,-74.006,40.269,48.789,5.748,5.035,52.005,0.654,80,10.603,48.530,5.464
226,2025-11-14 04:25:17.554219,US,New York,40.713,-74.006,44.250,83.417,1.819,9.634,63.057,0.111,88,17.197,32.595,0.591
256,2025-11-15 10:25:17.554219,US,New York,40.713,-74.006,41.904,3.347,4.424,7.354,33.211,0.376,83,13.580,80.338,8.541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17566,2025-11-16 16:25:17.554219,FI,Helsinki,60.170,24.938,64.531,98.586,0.326,1.873,70.459,0.542,129,6.235,44.693,7.308
17568,2025-11-16 18:25:17.554219,FI,Helsinki,60.170,24.938,49.471,70.450,3.879,3.647,62.212,0.676,98,25.879,29.066,2.558
17596,2025-11-17 22:25:17.554219,FI,Helsinki,60.170,24.938,73.736,83.998,1.977,6.281,46.863,1.039,147,21.737,70.312,8.156
17705,2025-11-07 11:25:17.554219,CH,Zurich,47.377,8.542,47.779,48.225,3.542,7.068,36.900,1.135,95,6.185,69.317,5.973
17951,2025-11-17 17:25:17.554219,CH,Zurich,47.377,8.542,56.553,54.765,2.930,7.967,26.985,0.133,113,23.582,31.741,3.718

In [75]:
#filtering data to access the or operator
df[(df["no2"]<6) |(df["temperature"]<30)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [76]:
#filtering data with high logics
df[(df["no2"]<6) &(df["temperature"]<30) & (df["pm25"]>5)]

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
99,2025-11-08 21:25:17.554219,US,New York,40.713,-74.006,28.589,46.458,1.252,4.613,54.452,1.019,57,28.134,27.374,2.585
152,2025-11-11 02:25:17.554219,US,New York,40.713,-74.006,32.981,90.472,4.891,6.073,34.687,0.976,90,6.430,40.777,9.852
175,2025-11-12 01:25:17.554219,US,New York,40.713,-74.006,40.269,48.789,5.748,5.035,52.005,0.654,80,10.603,48.530,5.464
226,2025-11-14 04:25:17.554219,US,New York,40.713,-74.006,44.250,83.417,1.819,9.634,63.057,0.111,88,17.197,32.595,0.591
256,2025-11-15 10:25:17.554219,US,New York,40.713,-74.006,41.904,3.347,4.424,7.354,33.211,0.376,83,13.580,80.338,8.541
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17566,2025-11-16 16:25:17.554219,FI,Helsinki,60.170,24.938,64.531,98.586,0.326,1.873,70.459,0.542,129,6.235,44.693,7.308
17568,2025-11-16 18:25:17.554219,FI,Helsinki,60.170,24.938,49.471,70.450,3.879,3.647,62.212,0.676,98,25.879,29.066,2.558
17596,2025-11-17 22:25:17.554219,FI,Helsinki,60.170,24.938,73.736,83.998,1.977,6.281,46.863,1.039,147,21.737,70.312,8.156
17705,2025-11-07 11:25:17.554219,CH,Zurich,47.377,8.542,47.779,48.225,3.542,7.068,36.900,1.135,95,6.185,69.317,5.973
17951,2025-11-17 17:25:17.554219,CH,Zurich,47.377,8.542,56.553,54.765,2.930,7.967,26.985,0.133,113,23.582,31.741,3.718

In [83]:
# I want only city and aqi deatails of no2 <6 , temperature< 30, pm25>5 only lets filter data 
df[(df["no2"]<6) &(df["temperature"]<30) & (df["pm25"]>5)] [["city", "aqi"]]

           city  aqi
99     New York   57
152    New York   90
175    New York   80
226    New York   88
256    New York   83
...         ...  ...
17566  Helsinki  129
17568  Helsinki   98
17596  Helsinki  147
17705    Zurich   95
17951    Zurich  113

[385 rows x 2 columns]

In [92]:
# filter data using Query
df.query("aqi<50 & temperature >30")[["city", "aqi"]]

               city  aqi
22         New York   49
43         New York   49
960          London   16
1396          Paris   46
1430          Paris   45
1677         Berlin   35
1690         Berlin   49
2729        Toronto   44
3159    Mexico City   40
3330      São Paulo   45
3417      São Paulo   41
3510      São Paulo   45
3650   Buenos Aires   44
4012      Cape Town   35
6111         Riyadh   48
6395           Doha   45
6799         Mumbai   44
7023          Delhi   48
7258      Bengaluru   46
8035        Chennai   43
9008          Seoul   43
9163          Seoul   45
9519        Beijing   42
11600       Jakarta   49
11763       Jakarta   48
12029        Sydney   49
12532     Melbourne   47
13733        Tehran   35
13798        Tehran   49
15505       Chicago   43
16169       Houston   39
16880        Warsaw   35
16957     Stockholm   48
17624      Helsinki   43
17713        Zurich   48
17962        Zurich   47

In [93]:
# filter data using Query and python var
aqi_value = 50
df.query("aqi< @aqi_value & temperature >30")[["city", "aqi"]]

               city  aqi
22         New York   49
43         New York   49
960          London   16
1396          Paris   46
1430          Paris   45
1677         Berlin   35
1690         Berlin   49
2729        Toronto   44
3159    Mexico City   40
3330      São Paulo   45
3417      São Paulo   41
3510      São Paulo   45
3650   Buenos Aires   44
4012      Cape Town   35
6111         Riyadh   48
6395           Doha   45
6799         Mumbai   44
7023          Delhi   48
7258      Bengaluru   46
8035        Chennai   43
9008          Seoul   43
9163          Seoul   45
9519        Beijing   42
11600       Jakarta   49
11763       Jakarta   48
12029        Sydney   49
12532     Melbourne   47
13733        Tehran   35
13798        Tehran   49
15505       Chicago   43
16169       Houston   39
16880        Warsaw   35
16957     Stockholm   48
17624      Helsinki   43
17713        Zurich   48
17962        Zurich   47